import dotenv from 'dotenv'

dotenv.config()

const data =
{
    "start" : "Привет, {username} 👋🏻 Я бот-переводчик. 😎 \n Я умею переводить на {length} языков. 🎓  \n Выбери команду: \n/translate - перевести текст \n/settings - настройка \n/about - о боте",
    "about": "Bot beta-version 1.4 \n🎓{length} languages.\n👤 Author " + process.env.author,
    "translate_do_not": "{username}, вы не выбрали язык.\nВыбрать язык /changeLanguage",
    "translate_choise": "Выбан язык {lang}\nВведите текст для перевода или отправьте текстовый файл:",
    "translate_msg": "{result}\nЕще раз? /translate\nИзменить язык /changeLanguage",
    "settings": "Выбрать язык /changeLanguage",
    "changeLanguage" : "Выбери на какой язык переводить. Например English",
    "choise_lang": "Язык установлен {lang} /translate"
}


const langs = {
    // 'auto': 'Automatic',
    // 'af': 'Afrikaans',
    // 'sq': 'Albanian',
    // 'am': 'Amharic',
    'ar': 'Arabic',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    // 'eu': 'Basque',
    // 'be': 'Belarusian',
    // 'bn': 'Bengali',
    // 'bs': 'Bosnian',
    // 'bg': 'Bulgarian',
    // 'ca': 'Catalan',
    // 'ceb': 'Cebuano',
    // 'ny': 'Chichewa',
    // 'zh': 'Chinese (Simplified)',
    // 'zh-cn': 'Chinese (Simplified)',
    // 'zh-tw': 'Chinese (Traditional)',
    // 'co': 'Corsican',
    // 'hr': 'Croatian',
    // 'cs': 'Czech',
    // 'da': 'Danish',
    // 'nl': 'Dutch',
    'en': 'English',
    // 'eo': 'Esperanto',
    // 'et': 'Estonian',
    // 'tl': 'Filipino',
    // 'fi': 'Finnish',
    'fr': 'French',
    // 'fy': 'Frisian',
    // 'gl': 'Galician',
    'ka': 'Georgian',
    'de': 'German',
    // 'el': 'Greek',
    // 'gu': 'Gujarati',
    // 'ht': 'Haitian Creole',
    // 'ha': 'Hausa',
    // 'haw': 'Hawaiian',
    // 'he': 'Hebrew',
    // 'iw': 'Hebrew',
    // 'hi': 'Hindi',
    // 'hmn': 'Hmong',
    // 'hu': 'Hungarian',
    // 'is': 'Icelandic',
    // 'ig': 'Igbo',
    // 'id': 'Indonesian',
    // 'ga': 'Irish',
    'it': 'Italian',
    // 'ja': 'Japanese',
    // 'jw': 'Javanese',
    // 'kn': 'Kannada',
    // 'kk': 'Kazakh',
    // 'km': 'Khmer',
    // 'ko': 'Korean',
    // 'ku': 'Kurdish (Kurmanji)',
    // 'ky': 'Kyrgyz',
    // 'lo': 'Lao',
    // 'la': 'Latin',
    // 'lv': 'Latvian',
    // 'lt': 'Lithuanian',
    // 'lb': 'Luxembourgish',
    // 'mk': 'Macedonian',
    // 'mg': 'Malagasy',
    // 'ms': 'Malay',
    // 'ml': 'Malayalam',
    // 'mt': 'Maltese',
    // 'mi': 'Maori',
    // 'mr': 'Marathi',
    // 'mn': 'Mongolian',
    // 'my': 'Myanmar (Burmese)',
    // 'ne': 'Nepali',
    // 'no': 'Norwegian',
    // 'ps': 'Pashto',
    // 'fa': 'Persian',
    'pl': 'Polish',
    // 'pt': 'Portuguese',
    // 'pa': 'Punjabi',
    // 'ro': 'Romanian',
    'ru': 'Russian',
    // 'sm': 'Samoan',
    // 'gd': 'Scots Gaelic',
    // 'sr': 'Serbian',
    // 'st': 'Sesotho',
    // 'sn': 'Shona',
    // 'sd': 'Sindhi',
    // 'si': 'Sinhala',
    // 'sk': 'Slovak',
    // 'sl': 'Slovenian',
    // 'so': 'Somali',
    'es': 'Spanish',
    // 'su': 'Sundanese',
    // 'sw': 'Swahili',
    // 'sv': 'Swedish',
    // 'tg': 'Tajik',
    // 'ta': 'Tamil',
    // 'te': 'Telugu',
    // 'th': 'Thai',
    // 'turk': 'Turkish',
    'uk': 'Ukrainian',
    // 'ur': 'Urdu',
    // 'uz': 'Uzbek',
    // 'vi': 'Vietnamese',
    // 'cy': 'Welsh',
    // 'xh': 'Xhosa',
    // 'yi': 'Yiddish',
    // 'yo': 'Yoruba',
    'zu': 'Zulu'
};  
 
export { data, langs }